adoptar/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('apps.posts.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('apps.users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/posts/urls.py
from django.urls import path
from .views import feed

app_name = 'posts'
urlpatterns = [
    path('', feed, name="feed")
]

apps/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

from django.urls import reverse_lazy

app_name = 'users'
urlpatterns = [
    path('login/', views.Login.as_view(redirect_authenticated_user=True), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('register/', views.Register.as_view(), name="register"),

    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name="users/password_change/change.html",success_url=reverse_lazy('users:password_change_done')), name="password_change"),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name="users/password_change/done.html"), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset/reset.html', 
        email_template_name='users/password_reset/email.html', 
        subject_template_name="users/password_reset/subject.txt",
        success_url=reverse_lazy('users:password_reset_done')), name="password_reset"),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset/done.html'), name="password_reset_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset/confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')), name="password_reset_confirm"),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset/complete.html'), name="password_reset_complete"),

    path("update/", views.UserUpdateProfile.as_view(), name="update_profile"),
    path('<str:username>/', views.UserProfile, name="profile"),

    path("ajax/load-cities", views.load_cities, name="ajax_load_cities"),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  <title>
    {% block title %}{% endblock title %}
  </title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #e3f2fd;">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'posts:feed' %}">Adopt.ar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if user.is_authenticated and user.is_staff %}
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="/admin/">Panel de administrador</a>
            </li>
          {% endif %}
        </ul>
        {% if request.user.is_authenticated %}
          <div class="dropdown mx-3">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
              {{ user.username }}
            </button>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton1">
              <li>
                <a class="dropdown-item" href="{% url 'users:profile' user.username %}">Mi perfil</a>
              </li>
              <li>
                <button type="button" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                  Cerrar sesión
                </button>
              </li>
            </ul>
          </div>
          
        {% else %}
          <div class="btn-group mx-3">
            <a href="{% url 'users:login' %}" class="btn btn-primary">Ingresar</a>
            <a href="{% url 'users:register' %}" class="btn btn-primary">Registrarse</a>
          </div>
        {% endif %}
      </div>
    </div>
  </nav>

  <div class="container-lg mt-4">
    {% block content %}
    {% endblock content %}

    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="staticBackdropLabel">Cerrar sesión</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <p>¿Quiere terminar su sesión?</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
            <a href="{% url 'users:logout' %}" type="button" class="btn btn-danger">Cerrar sesión</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Scripts -->
  <!-- Bootstrap script -->
  <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  {% block javascript %}{% endblock javascript %}
</body>
</html>