adoptar/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('apps.posts.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('apps.users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

from django.urls import reverse_lazy

app_name = 'users'
urlpatterns = [
    path('login/', views.Login.as_view(redirect_authenticated_user=True), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('register/', views.Register.as_view(), name="register"),

    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name="users/password_change/change.html",success_url=reverse_lazy('users:password_change_done')), name="password_change"),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name="users/password_change/done.html"), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset/reset.html', 
        email_template_name='users/password_reset/email.html', 
        subject_template_name="users/password_reset/subject.txt",
        success_url=reverse_lazy('users:password_reset_done')), name="password_reset"),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset/done.html'), name="password_reset_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset/confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')), name="password_reset_confirm"),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset/complete.html'), name="password_reset_complete"),

    path("update/", views.UserUpdateProfile.as_view(), name="update_profile"),
    path('<str:username>/', views.UserProfile, name="profile"),

    path("ajax/load-cities", views.load_cities, name="ajax_load_cities"),
]

apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from adoptar.settings.base import MEDIA_URL, STATIC_URL

# Create your models here.
class Province(models.Model):
    name = models.CharField(verbose_name="nombre", max_length=100)

    class Meta:
        verbose_name = 'provincia'
        verbose_name_plural = 'provincias'

    def __str__(self):
        return self.name

class City(models.Model):
    name = models.CharField(verbose_name="nombre", max_length=200)
    province = models.ForeignKey(Province, verbose_name="provincia", on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'ciudad'
        verbose_name_plural = 'ciudades'

    def __str__(self):
        return self.name
    
class User(AbstractUser):
    avatar = models.ImageField(verbose_name="avatar", upload_to="users/%Y/%m/%d",  null=True, blank=True)
    description = models.TextField(verbose_name="descripción", blank=True, null=True, max_length=250)
    province = models.ForeignKey(Province, verbose_name="provincia", on_delete=models.SET_NULL, null=True, blank=True, default=None)
    city = models.ForeignKey(City, verbose_name="ciudad", on_delete=models.SET_NULL, null=True, blank=True, default=None)

    def get_avatar(self):
        if self.avatar:
            return '{}{}'.format(MEDIA_URL, self.avatar)
        return '{}{}'.format(STATIC_URL, 'images/empty.png')

class Reason(models.Model):
    title = models.CharField(verbose_name='título', max_length=100)

    class Meta:
        verbose_name = 'razón'
        verbose_name_plural = 'razones'

    def __str__(self):
        return self.title

class Complaint(models.Model):
    reason = models.ForeignKey(Reason, verbose_name="razón", on_delete=models.SET_DEFAULT, default="Razón")
    from_user = models.ForeignKey(User, verbose_name="denunciador", on_delete=models.SET_DEFAULT, default="Usuario", related_name="complaint_from_user")
    to_user = models.ForeignKey(User, verbose_name="denunciado", on_delete=models.DO_NOTHING, related_name="complaint_to_user")
    created_at = models.DateTimeField("created_at", auto_now_add=True)
    comment = models.CharField("comentario", max_length=200, null=True, default=None)

    class Meta:
        verbose_name = 'denuncia'
        verbose_name_plural = 'denuncias'

    def __str__(self):
        return "Denuncia #%s" % (self.pk)

class Qualification(models.Model):
    from_user = models.ForeignKey(User, verbose_name="calificador", on_delete=models.SET_DEFAULT, default="Usuario", related_name="qualification_from_user")
    to_user = models.ForeignKey(User, verbose_name="calificado", on_delete=models.CASCADE, related_name="qualification_to_user")
    score = models.SmallIntegerField(verbose_name="puntución")
    date = models.DateField(verbose_name="created_at", auto_now_add=True)
    comment = models.CharField("comentario", max_length=200, null=True, default=None)

    class Meta:
        verbose_name = 'calificación'
        verbose_name_plural = 'calificaciones'

    def __str__(self):
        return "Puntuación %d - Usuario: %s" % (self.score, self.to_user.username)

apps/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import User, City

class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'province',
            'password1',
            'password2'
        ]

        help_texts = {
            k: "" for k in fields
        }

class UpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email',
            'avatar',
            'description',
            'province',
            'city'
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()

        if 'province' in self.data:
            try:
                province_id = int(self.data.get('province'))
                self.fields['city'].queryset = City.objects.filter(province=province_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.province:
            self.fields['city'].queryset = self.instance.province.city_set.order_by('name')

apps/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView, LogoutView, login_required
from django.views.generic import CreateView, UpdateView
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin

from django.urls import reverse_lazy
from .forms import RegistrationForm, UpdateForm

from .models import User, City

# Create your views here.
class Login(LoginView):
    template_name = 'users/login.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'Iniciar sesión'
        return context
class Register(CreateView):
    form_class = RegistrationForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('posts:feed')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('posts:feed')
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'Crear cuenta'
        return context

    def form_valid(self, form):
        valid = super(Register, self).form_valid(form)
        username, password = form.cleaned_data.get('username'), form.cleaned_data.get('password1')
        new_user = authenticate(self.request, username=username, password=password)
        login(self.request, new_user)
        return valid

class UserUpdateProfile(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'users/update.html'
    form_class = UpdateForm

    def get_object(self):
        return self.request.user

    def get_success_url(self):
        return reverse_lazy('users:profile', kwargs={'username': self.request.user.username })

# AJAX
def load_cities(request):
    province_id = request.GET.get('province')
    cities = City.objects.filter(province=province_id).order_by('name')
    return render(request, 'users/cities_list_options.html', { 'cities': cities })

@login_required
def UserProfile(request, username):
    user = User.objects.get(username=username)
    return render(request, 'users/profile.html', { 'profile': user })

templates/users/cities_list_options.html
<option hidden selected disabled value="">---------</option>
{% for city in cities %}
    <option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

templates/users/login.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
  {{ title }}
{% endblock title %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col col-md-4">
      <div class="card mb-3">
        <div class="card-header">
          {{ title }}
        </div>
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group mb-3">
                <label for="" class="form-label">{{ field.label }}</label>
                {{ field|add_class:'form-control' }}
              </div>
            {% endfor %}
            <div class="d-grid gap-2">
              <button type="submit" class="btn btn-primary">Iniciar sesión</button>
              <span class="text-center">
                ¿Olvido su contraseña? <a href="{% url 'users:password_reset' %}">Recuperar contraseña</a>
              </span>
              <span class="text-center">
                ¿No tienes cuenta? <a href="{% url 'users:register' %}">Crea una</a>
              </span>
            </div>
          </form>
        </div>
      </div>

      {% if form.errors %}
        {% for field in form %}
          {% for error in field.errors %}
            <div class="alert alert-danger">
              <strong>{{ error|escape }}</strong>
            </div>
          {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
          </div>
        {% endfor %}
      {% endif %}
    </div>
  </div>
{% endblock content %}

templates/users/profile.html
{% extends 'base.html' %}

{% block title %}
  {{ profile.username }}
{% endblock title %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col">
      <div class="card">
        <div class="card-body">
          <div class="row">
            <div class="col-md" style="border-right: 1px solid #dee2e6;">
              <div class="row">
                <div class="col-md-4">
                  <img src="{{ profile.get_avatar }}" alt="User avatar" class="img-thumbnail mb-3">
                  <p class="text-muted">
                    {% if profile.description %}
                      {{ profile.description }}
                    {% elif user.id == profile.id %}
                      ¡Cuenta algo sobre ti!
                    {% else %}
                      Este usuario no tiene una descripción
                    {% endif %}
                  </p>
                </div>
                <div class="col-md">
                  <h2 class="mb-3">{{ profile.first_name }} {{ profile.last_name }}</h2>
                  <table class="table table-responsive table-hover">
                    <tbody>
                      <tr>
                        <th>Nombre de usuario:</th>
                        <td>{{ profile.username }}</td>
                      </tr>
                      <tr>
                        <th>Email:</th>
                        <td>{{ profile.email }}</td>
                      </tr>
                      <tr>
                        <th>Provincia:</th>
                        <td>{{ profile.province }}</td>
                      </tr>
                      <tr>
                        <th>Ciudad:</th>
                        <td>
                          {% if profile.city %}
                            {{ profile.city }}
                          {% else %}
                            No especificado
                          {% endif %}
                        </td>
                      </tr>
                      <tr>
                        <th>Ultimo ingreso:</th>
                        <td>{{ profile.last_login }}</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
            <div class="col-lg text-center">
              <h2>Ultimas calificaciones</h2>
              {% if profile.qualifications %}
              {% else %}
                No existen calificaciones
              {% endif %}
            </div>
          </div>
        </div>
        <div class="card-footer">
          {% if user.id == profile.id %}
            <a href="{% url 'users:update_profile' %}" class="btn btn-primary">Editar perfil</a>
            <a href="{% url 'users:password_change' %}" class="btn btn-primary">Cambiar contraseña</a>
          {% else %}
            <a href="#" type="button" class="btn btn-danger">Denunciar usuario</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/users/register.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
  Crear cuenta
{% endblock title %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col col-md-4">
      <div class="card mb-3">
        <div class="card-header">Crear cuenta</div>
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group mb-3">
                <label for="" class="form-label">{{ field.label }}:</label>
                {{ field|add_class:'form-control' }}
              </div>
            {% endfor %}
            <div class="d-grid gap-2">
              <button type="submit" class="btn btn-primary">Crear cuenta</button>
              <span class="text-center">
                ¿Tienes cuenta? <a href="{% url 'users:login' %}">Iniciar sesión</a>
              </span>
            </div>
          </form>
        </div>
      </div>

      {% if form.errors %}
        {% for field in form %}
          {% for error in field.errors %}
            <div class="alert alert-danger">
              <strong>{{ error|escape }}</strong>
            </div>
          {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
          </div>
        {% endfor %}
      {% endif %}
    </div>
  </div>
{% endblock content %}

templates/users/update.html
{% extends 'base.html' %}

{% load static %}
{% load widget_tweaks %}

{% block title %}
  Actualizar perfil
{% endblock title %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col">
      <div class="card mb-3">
        <form method="post" id="updateUser" data-cities-url="{% url 'users:ajax_load_cities' %}" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="card-body">
            <div class="row">
              <div class="col-md-3">
                <img src="{{ user.get_avatar }}" alt="User avatar" class="mb-3 img-thumbnail">
                <div class="form-group mb-3">
                  <label for="{{ form.description.html_name }}" class="form-label">{{ form.description.label }}</label>
                  {{ form.description|add_class:'form-control' }}
                </div>
              </div>
              <div class="col">
                <div class="form-group mb-3">
                  <label for="{{ form.first_name.html_name }}" class="form-label">{{ form.first_name.label }}</label>
                  {{ form.first_name|add_class:'form-control' }}
                </div>

                <div class="form-group mb-3">
                  <label for="{{ form.last_name.html_name }}" class="form-label">{{ form.last_name.label }}</label>
                  {{ form.last_name|add_class:'form-control' }}
                </div>

                <div class="form-group mb-3">
                  <label for="{{ form.avatar.html_name }}">{{ form.avatar.label }}</label>
                  {{ form.avatar|add_class:'form-control' }}
                </div>

                <div class="form-group mb-3">
                  <label for="{{ form.email.html_name }}" class="form-label">{{ form.email.label }}</label>
                  {{ form.email|add_class:'form-control' }}
                </div>

                <div class="form-group mb-3">
                  <label for="{{ form.province.html_name }}" class="form-label">{{ form.province.label }}</label>
                  {{ form.province|add_class:'form-control' }}
                </div>

                <div class="form-group mb-3">
                  <label for="{{ form.city.html_name }}" class="form-label">{{ form.city.label }}</label>
                  {{ form.city|add_class:'form-control' }}
                </div>
              </div>
            </div>
          </div>
          <div class="card-footer">
            <button type="submit" class="btn btn-primary">Actualizar perfil</button>
            <a href="{% url 'users:profile' user.username %}" class="btn btn-danger">Cancelar</a>
          </div>
        </form>
      </div>

      {% if form.errors %}
        {% for field in form %}
          {% for error in field.errors %}
            <div class="alert alert-danger">
              <strong>{{ error|escape }}</strong>
            </div>
          {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
          </div>
        {% endfor %}
      {% endif %}
    </div>
  </div>
{% endblock content %}

{% block javascript %}
  <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
  <script>
    $("#id_province").change(function (){
      var url = $("#updateUser").attr("data-cities-url");
      var provinceId = $(this).val();

      $.ajax({
        url: url,
        data: {
          'province': provinceId
        },
        success: function(data) {
          $("#id_city").html(data)
        }
      });
    });
  </script>
{% endblock javascript %}