adoptar/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('apps.posts.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('apps.users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

from django.urls import reverse_lazy

app_name = 'users'
urlpatterns = [
    path('login/', views.Login.as_view(redirect_authenticated_user=True), name="login"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('register/', views.Register.as_view(), name="register"),

    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name="users/password_change/change.html",success_url=reverse_lazy('users:password_change_done')), name="password_change"),

    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name="users/password_change/done.html"), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='users/password_reset/reset.html', 
        email_template_name='users/password_reset/email.html', 
        subject_template_name="users/password_reset/subject.txt",
        success_url=reverse_lazy('users:password_reset_done')), name="password_reset"),

    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='users/password_reset/done.html'), name="password_reset_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset/confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')), name="password_reset_confirm"),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset/complete.html'), name="password_reset_complete"),

    path("update/", views.UserUpdateProfile.as_view(), name="update_profile"),
    path('<str:username>/', views.UserProfile, name="profile"),

    path("ajax/load-cities", views.load_cities, name="ajax_load_cities"),
]

apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from adoptar.settings.base import MEDIA_URL, STATIC_URL

# Create your models here.
class Province(models.Model):
    name = models.CharField(verbose_name="nombre", max_length=100)

    class Meta:
        verbose_name = 'provincia'
        verbose_name_plural = 'provincias'

    def __str__(self):
        return self.name

class City(models.Model):
    name = models.CharField(verbose_name="nombre", max_length=200)
    province = models.ForeignKey(Province, verbose_name="provincia", on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'ciudad'
        verbose_name_plural = 'ciudades'

    def __str__(self):
        return self.name
    
class User(AbstractUser):
    avatar = models.ImageField(verbose_name="avatar", upload_to="users/%Y/%m/%d",  null=True, blank=True)
    description = models.TextField(verbose_name="descripción", blank=True, null=True, max_length=250)
    province = models.ForeignKey(Province, verbose_name="provincia", on_delete=models.SET_NULL, null=True, blank=True, default=None)
    city = models.ForeignKey(City, verbose_name="ciudad", on_delete=models.SET_NULL, null=True, blank=True, default=None)

    def get_avatar(self):
        if self.avatar:
            return '{}{}'.format(MEDIA_URL, self.avatar)
        return '{}{}'.format(STATIC_URL, 'images/empty.png')

class Reason(models.Model):
    title = models.CharField(verbose_name='título', max_length=100)

    class Meta:
        verbose_name = 'razón'
        verbose_name_plural = 'razones'

    def __str__(self):
        return self.title

class Complaint(models.Model):
    reason = models.ForeignKey(Reason, verbose_name="razón", on_delete=models.SET_DEFAULT, default="Razón")
    from_user = models.ForeignKey(User, verbose_name="denunciador", on_delete=models.SET_DEFAULT, default="Usuario", related_name="complaint_from_user")
    to_user = models.ForeignKey(User, verbose_name="denunciado", on_delete=models.DO_NOTHING, related_name="complaint_to_user")
    created_at = models.DateTimeField("created_at", auto_now_add=True)
    comment = models.CharField("comentario", max_length=200, null=True, default=None)

    class Meta:
        verbose_name = 'denuncia'
        verbose_name_plural = 'denuncias'

    def __str__(self):
        return "Denuncia #%s" % (self.pk)

class Qualification(models.Model):
    from_user = models.ForeignKey(User, verbose_name="calificador", on_delete=models.SET_DEFAULT, default="Usuario", related_name="qualification_from_user")
    to_user = models.ForeignKey(User, verbose_name="calificado", on_delete=models.CASCADE, related_name="qualification_to_user")
    score = models.SmallIntegerField(verbose_name="puntución")
    date = models.DateField(verbose_name="created_at", auto_now_add=True)
    comment = models.CharField("comentario", max_length=200, null=True, default=None)

    class Meta:
        verbose_name = 'calificación'
        verbose_name_plural = 'calificaciones'

    def __str__(self):
        return "Puntuación %d - Usuario: %s" % (self.score, self.to_user.username)

apps/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import User, City

class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'province',
            'password1',
            'password2'
        ]

        help_texts = {
            k: "" for k in fields
        }

class UpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email',
            'avatar',
            'description',
            'province',
            'city'
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['city'].queryset = City.objects.none()

        if 'province' in self.data:
            try:
                province_id = int(self.data.get('province'))
                self.fields['city'].queryset = City.objects.filter(province=province_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.province:
            self.fields['city'].queryset = self.instance.province.city_set.order_by('name')

apps/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView, LogoutView, login_required
from django.views.generic import CreateView, UpdateView
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin

from django.urls import reverse_lazy
from .forms import RegistrationForm, UpdateForm

from .models import User, City

# Create your views here.
class Login(LoginView):
    template_name = 'users/login.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'Iniciar sesión'
        return context
class Register(CreateView):
    form_class = RegistrationForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('posts:feed')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('posts:feed')
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'Crear cuenta'
        return context

    def form_valid(self, form):
        valid = super(Register, self).form_valid(form)
        username, password = form.cleaned_data.get('username'), form.cleaned_data.get('password1')
        new_user = authenticate(self.request, username=username, password=password)
        login(self.request, new_user)
        return valid

class UserUpdateProfile(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'users/update.html'
    form_class = UpdateForm

    def get_object(self):
        return self.request.user

    def get_success_url(self):
        return reverse_lazy('users:profile', kwargs={'username': self.request.user.username })

# AJAX
def load_cities(request):
    province_id = request.GET.get('province')
    cities = City.objects.filter(province=province_id).order_by('name')
    return render(request, 'users/cities_list_options.html', { 'cities': cities })

@login_required
def UserProfile(request, username):
    user = User.objects.get(username=username)
    return render(request, 'users/profile.html', { 'profile': user })

templates/users/password_reset/complete.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}Recuperar contraseña{% endblock title %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col col-md-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title mb-4">Reinicio de contraseña completado</h5>
          <p class="text">
            Su contraseña ha sido cambiada. Ahora puede continuar e ingresar.
          </p>

          <div class="d-grid gap-2">
            <span class="text-center">
              <a href="{% url 'users:login' %}">Identificarse</a>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/users/password_reset/confirm.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}Recuperar contraseña{% endblock title %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col col-md-6">
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title">Introduzca nueva contraseña</h5>
          <p class="text">
            Por favor introduzca su nueva contraseña dos veces de manera que podamos verificar que la ha escrito correctamente.
          </p>

          <form method="post">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group mb-3">
                <label for="" class="form-label">{{ field.label }}:</label>
                {{ field|add_class:'form-control' }}
              </div>
            {% endfor %}

            <div class="d-grid gap-2">
              <button type="submit" class="btn btn-primary">Cambiar contraseña</button>
            </div>
          </form>
        </div>
      </div>

      {% if form.errors %}
        {% for field in form %}
          {% for error in field.errors %}
            <div class="alert alert-danger">
              <strong>{{ error|escape }}</strong>
            </div>
          {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
          </div>
        {% endfor %}
      {% endif %}
    </div>
  </div>
{% endblock content %}

templates/users/password_reset/done.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}Recuperar contraseña{% endblock title %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col col-md-6">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title mb-4">Se ha enviado un email de reinicialización de contraseña</h5>
          <p class="text">
            Se le han enviado instrucciones sobre cómo establecer su contraseña. Si la dirección de email que proveyó existe, debería recibir las mismas pronto.
          </p>
          <p class="text">
            Si no ha recibido un email, por favor asegúrese de que ha introducido la dirección de correo con la que se había registrado y verifique su carpeta de Correo no deseado.
          </p>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/users/password_reset/email.html
Le enviamos este email porque Ud. ha solicitado que se reestablezca la contraseña para su cuenta de usuario en Adopt.ar

Por favor visite la página que se muestra a continuación y elija una nueva contraseña:

{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}



Su nombre de usuario en caso de que lo haya olvidado: {{ user.get_username }}
Si usted no solicito que se reestablezca la contraseña, simplemente ignore este mensaje.

¡Gracias por usar nuestro sitio!

El equipo de Adopt.ar

templates/users/password_reset/reset.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}Recuperar contraseña{% endblock title %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col col-md-6">
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title">¿Olvidaste tu contraseña?</h5>
          <p class="text">
              Introduzca su dirección de email abajo y le enviaremos instrucciones para establecer una nueva.
          </p>

          <form method="post">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group mb-3">
                <label for="" class="form-label">{{ field.label }}:</label>
                {{ field|add_class:'form-control' }}
              </div>
            {% endfor %}

            <div class="d-grid gap-2">
              <button type="submit" class="btn btn-primary">Enviar email</button>
            </div>
          </form>
        </div>
      </div>

      {% if form.errors %}
        {% for field in form %}
          {% for error in field.errors %}
            <div class="alert alert-danger">
              <strong>{{ error|escape }}</strong>
            </div>
          {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
          </div>
        {% endfor %}
      {% endif %}
    </div>
  </div>
{% endblock content %}